export { default as Contact } from './Contact/Contact'
export { default as Landing } from './Landing/Landing'
export { default as Projects } from './Projects/Projects'
export { default as Skills } from './Skills/Skills'
export { default as Testimonials } from './Testimonials/Testimonials'
